import * as React from "react";
import Svg, { Rect } from "react-native-svg";

function SvgAppsOutline(props) {
  return (
    <Svg width="1em" height="1em" viewBox="0 0 512 512" {...props}>
      <Rect
        x={64}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={216}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={368}
        y={64}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={64}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={216}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={368}
        y={216}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={64}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={216}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
      <Rect
        x={368}
        y={368}
        width={80}
        height={80}
        rx={40}
        ry={40}
        fill="none"
        stroke="#000"
        strokeMiterlimit={10}
        strokeWidth={32}
      />
    </Svg>
  );
}

export default SvgAppsOutline;

