import * as React from "react";
import Svg, { Rect } from "react-native-svg";

function SvgFilmOutline(props) { 
  const strokeWidth = props.strokeWidth ? props.strokeWidth : 32
  return (
    <Svg width="1em" height="1em" viewBox="0 0 512 512" {...props}>
      <Rect
        x={48}
        y={96}
        width={416}
        height={320}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={384}
        y={336}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={384}
        y={256}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={384}
        y={176}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={384}
        y={96}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={48}
        y={336}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={48}
        y={256}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={48}
        y={176}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={48}
        y={96}
        width={80}
        height={80}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={128}
        y={96}
        width={256}
        height={160}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
      <Rect
        x={128}
        y={256}
        width={256}
        height={160}
        rx={28}
        ry={28}
        fill={props.fill}
        stroke={props.color}
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      />
    </Svg>
  );
}

export default SvgFilmOutline;

